### ISSUE TITLE
请求大佬添加docker支持

### ISSUE THREAD

**Issue by spysir** [zfb132/frp_info#2]
- python环境搭建感觉有点麻烦，如果能支持docker就方便多了
- 此外，之前我用过arugal/frp-notify这个插件，当客户端网络不稳定时，客户端每重连一次通知就推送一次，感觉有点烦人，如果frp_info能设置IP白名单或者设置时间限制就好了

**Comment by zfb132** [comment]
@spysir 已添加docker  
如果设置指定客户端上线免打扰的话，大概需要再维护一个名单，不是很合理。你可以fork一下，在下面判断客户端是否需要免打扰即可  
https://github.com/zfb132/frp_info/blob/bef58e36f9861bec6228c5f98c5145e8b79a8598/app/model/HandleFrpMsg.py#L21-L27
